name: efficient_builder
description: An Alternative to ValueListenableBuilder in Flutter.
version: 1.0.1
repository: https://github.com/Rayhan1546/Efficient-Builder

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



